language: node_js
node_js:
  - '10'
script:
  - npm run build # jest test with coverage flag does coverage too
  - npm run test
  - npm run test:e2e
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls' # sends the coverage report to coveralls
